# BATTERIA
# warning dopo 2m50s, lock dopo 3m, suspend dopo 3m30s
# BATTERIA - TEST

listener {
    timeout = 170
    on-timeout = sh -c 'if ! ~/.config/hypr/scripts/is-on-ac.sh; then ~/.config/hypr/scripts/prelock-countdown.sh; fi'
    on-resume = pkill -f prelock-countdown.sh
}

listener {
    timeout = 180
    on-timeout = sh -c 'if ! ~/.config/hypr/scripts/is-on-ac.sh && ! playerctl --ignore-player=spotify status 2>/dev/null | grep -q Playing; then hyprlock; fi'
}

listener {
    timeout = 210
    on-timeout = sh -c 'if ! ~/.config/hypr/scripts/is-on-ac.sh && ! playerctl --ignore-player=spotify status 2>/dev/null | grep -q Playing; then systemctl suspend; fi'
}

# IN CARICA
# warning dopo 9m50s, lock dopo 10m, suspend dopo 20m

listener {
    timeout = 590				
    on-timeout = sh -c 'if ~/.config/hypr/scripts/is-on-ac.sh; then ~/.config/hypr/scripts/prelock-countdown.sh; fi'
    on-resume = pkill -f prelock-countdown.sh
}

listener {
    timeout = 600	
    on-timeout = sh -c 'if ~/.config/hypr/scripts/is-on-ac.sh && ! playerctl --ignore-player=spotify status 2>/dev/null | grep -q Playing; then hyprlock; fi'
}

listener {
    timeout = 630
    on-timeout = sh -c 'if ~/.config/hypr/scripts/is-on-ac.sh && ! playerctl --ignore-player=spotify status 2>/dev/null | grep -q Playing; then systemctl suspend; fi'
}
