general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = ~/.config/hypr/scripts/resuspend-if-locked.sh
}

listener {
    timeout = 420
    on-timeout = sh -c 'if ! playerctl --ignore-player=spotify status 2>/dev/null | grep -q Playing; then loginctl lock-session; fi'
}

listener {
    timeout = 450
    on-timeout = sh -c 'if ! playerctl --ignore-player=spotify status 2>/dev/null | grep -q Playing; then systemctl suspend; fi'
}
