wallpaper {
    monitor = eDP-1
    path = /home/cobi/Documenti/Immagini/Sfondi/Actual/876589.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/cobi/Documenti/Immagini/Sfondi/Actual/876589.jpg
    fit_mode = cover
}
