#exec-once = waybar
exec-once = ~/Scripts/notification-sound.sh
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent
#exec-once = hyprpm reload
exec-once = ~/clipryx/publish/clipryx --daemon
exec-once = hypridle
exec-once = qs -c overview
exec-once = qs -c noctalia-shell
# exec-once = numlockx on
