windowrule = float on, match:class ^(kitty)$, match:title ^(btop)$
windowrule = size 900 600, match:class ^(kitty)$, match:title ^(btop)$
windowrule = center on, match:class ^(kitty)$, match:title ^(btop)$

windowrule = float on, size 650 450, move (monitor_w-650-10) 45, match:class ^(nmtui-go)$
windowrule = float on, size 650 450, move (monitor_w-650-10) 45, match:class ^(bluetui)$
windowrule = float on, size 650 450, move (monitor_w-650-10) 45, match:class ^(calendar-popup)$

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}
