#plugin {
#    hyprexpo {
#        columns = 3
#        gap_size = 12
#        bg_col = rgba(000000aa)
#        workspace_method = workspace 1
#        hyprexpo-gesture = 3, up, expo
#        skip_empty = false
#    }
#}
